export const BOOKS_UPDATE_LIST = 'BOOKS_UPDATE_LIST';
export const BOOKS_SET_FETCHING = 'BOOKS_SET_FETCHING';
export const BOOKS_UPDATE_ITEM = 'BOOKS_UPDATE_ITEM';
export const BOOKS_UPDATE_OFFSET = 'BOOKS_UPDATE_OFFSET';
export const BOOKS_UPDATE_SEARCH_QUERY = 'BOOKS_UPDATE_SEARCH_QUERY';
